const PianoUrlMap = {
  'A3': '/audio/piano/A3.mp3',
  'A4': '/audio/piano/A4.mp3',
  'A5': '/audio/piano/A5.mp3',
  'A#3': '/audio/piano/As3.mp3',
  'A#4': '/audio/piano/As4.mp3',
  'A#5': '/audio/piano/As5.mp3',
  'B3': '/audio/piano/B3.mp3',
  'B4': '/audio/piano/B4.mp3',
  'B5': '/audio/piano/B5.mp3',
  'C3': '/audio/piano/C3.mp3',
  'C4': '/audio/piano/C4.mp3',
  'C5': '/audio/piano/C5.mp3',
  'C#3': '/audio/piano/Cs3.mp3',
  'C#4': '/audio/piano/Cs4.mp3',
  'C#5': '/audio/piano/Cs5.mp3',
  'D3': '/audio/piano/D3.mp3',
  'D4': '/audio/piano/D4.mp3',
  'D5': '/audio/piano/D5.mp3',
  'D#3': '/audio/piano/Ds3.mp3',
  'D#4': '/audio/piano/Ds4.mp3',
  'D#5': '/audio/piano/Ds5.mp3',
  'E3': '/audio/piano/E3.mp3',
  'E4': '/audio/piano/E4.mp3',
  'E5': '/audio/piano/E5.mp3',
  'F3': '/audio/piano/F3.mp3',
  'F4': '/audio/piano/F4.mp3',
  'F5': '/audio/piano/F5.mp3',
  'F#3': '/audio/piano/Fs3.mp3',
  'F#4': '/audio/piano/Fs4.mp3',
  'F#5': '/audio/piano/Fs5.mp3',
  'G3': '/audio/piano/G3.mp3',
  'G4': '/audio/piano/G4.mp3',
  'G5': '/audio/piano/G5.mp3',
  'G#3': '/audio/piano/Gs3.mp3',
  'G#5': '/audio/piano/Gs5.mp3',
  'G#4': '/audio/piano/Gs4.mp3',
}

export default PianoUrlMap
